name: Aprendiendo GitActions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name Checkout
      uses: actions/checkout@v3
    - name: Definir variables
      run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
    - name: Correr script
      run: python hola-mundo.py
    
